<a href="https://colab.research.google.com/github/cristian0527/MATH-383/blob/main/Final_Project_Pre_Work_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Final Group Project Warmup #2

https://github.com/cristian0527/MATH-383/

In [ ]:
import networkx as nx
import matplotlib.pyplot as plt
import numpy as np
from networkx.readwrite import json_graph
import json

In [ ]:
# import classrooms
networks = []
#[1,2,3,4,5,6, 7, 8]
for i in [8]:

    with open(f'./classroom_{i}.json') as f:
        data = json.load(f)
        networks.append(json_graph.adjacency_graph(data))

In [ ]:
node_shapes = [[] for x in range(len(networks))]
shape_dict = {'MALE': 'o', 'FEMALE':'s'}
"""
for i in range(len(networks)):
    kk0 = nx.kamada_kawai_layout(networks[i])

    nx.draw_networkx_nodes(networks[i],pos=kk0,node_shape = 'd',
                           nodelist = [x for x in networks[i].nodes() if networks[i].nodes[x]['Gender']=='MALE'],
                           node_color=[networks[i].nodes[x]['Risk'] for x in networks[i].nodes() if networks[i].nodes[x]['Gender']=='MALE'],cmap='jet',
                           node_size = [networks[i].nodes[x]['CELF']*25 for x in networks[i].nodes() if networks[i].nodes[x]['Gender']=='MALE'])

    nx.draw_networkx_nodes(networks[i],pos=kk0,node_shape = 'o',  # ← was 3 spaces, now 4
                           nodelist = [x for x in networks[i].nodes() if networks[i].nodes[x]['Gender']=='FEMALE'],
                           node_color=[networks[i].nodes[x]['Risk'] for x in networks[i].nodes() if networks[i].nodes[x]['Gender']=='FEMALE'],
                           cmap='jet',node_size = [networks[i].nodes[x]['CELF']*25 for x in networks[i].nodes() if networks[i].nodes[x]['Gender']=='FEMALE'])

    nx.draw_networkx_edges(networks[i],pos = kk0)

    plt.axis('off')
    plt.show()
"""

"\nfor i in range(len(networks)):\n    kk0 = nx.kamada_kawai_layout(networks[i])\n\n    nx.draw_networkx_nodes(networks[i],pos=kk0,node_shape = 'd', \n                           nodelist = [x for x in networks[i].nodes() if networks[i].nodes[x]['Gender']=='MALE'],\n                           node_color=[networks[i].nodes[x]['Risk'] for x in networks[i].nodes() if networks[i].nodes[x]['Gender']=='MALE'],cmap='jet',\n                           node_size = [networks[i].nodes[x]['CELF']*25 for x in networks[i].nodes() if networks[i].nodes[x]['Gender']=='MALE'])\n\n    nx.draw_networkx_nodes(networks[i],pos=kk0,node_shape = 'o',  # ← was 3 spaces, now 4\n                           nodelist = [x for x in networks[i].nodes() if networks[i].nodes[x]['Gender']=='FEMALE'],\n                           node_color=[networks[i].nodes[x]['Risk'] for x in networks[i].nodes() if networks[i].nodes[x]['Gender']=='FEMALE'],\n                           cmap='jet',node_size = [networks[i].nodes[x]['CELF']*25 for x in networks[i].nodes() if networks[i].nodes[x]['Gender']=='FEMALE'])\n\n    nx.draw_networkx_edges(networks[i],pos = kk0)\n\n    plt.axis('off')\n    plt.show()\n"

## Part 1

#### P1; A
I will be investigating classroom 8

#### P1; B
Descriptive Statistics - Classroom 8

In [ ]:
# Descriptive Stats. for classroom 8
# networks[7]
G_8 = networks[0]

# number of vertices
n_vertices = G_8.number_of_nodes()

# the number of edges
n_edges = G_8.number_of_edges()

# the number of triangles
n_triangles = sum(nx.triangles(G_8).values()) // 3

# the proportion of students of each gender
genders = [G_8.nodes[x]['Gender'] for x in G_8.nodes()]
n_male   = genders.count('MALE')
n_female = genders.count('FEMALE')

male_prop = n_male/n_vertices
female_prop = n_female/n_vertices

# the proportion of students at risk in each classroom.
risk = [G_8.nodes[x]['Risk'] for x in G_8]
n_risk = risk.count(1)
n_not_risk = risk.count(0)

risk_prop = n_risk/n_vertices
not_risk_prop = n_not_risk/n_vertices

#### P1; C
proportion of friends of that node that are female and the proportion of friends of that node that are at risk. Then compute the averages of these values across each group of students.

In [ ]:
female = []
risk = []

for node in G_8.nodes():
    count_f = 0
    count_r = 0
    for neighbor in G_8.neighbors(node):
        if G_8.nodes[neighbor]['Gender'] == 'FEMALE':
            count_f += 1
        if G_8.nodes[neighbor]['Risk'] == 1:
            count_r += 1
    female.append(count_f / float(G_8.degree(node)))
    risk.append(count_r / float(G_8.degree(node)))

In [ ]:
print(f"the proportion of friends of that node that are female: {np.mean(female)}")
print(f"the proportion of friends of that node that are at risk: {np.mean(risk)}")

the proportion of friends of that node that are female: 0.4545351473922903
the proportion of friends of that node that are at risk: 0.5196145124716554

#### P1; D

In [ ]:
from itertools import combinations
import pandas as pd

same_gender_edge, same_gender_no_edge = 0, 0
diff_gender_edge, diff_gender_no_edge = 0, 0

same_risk_edge, same_risk_no_edge = 0, 0
diff_risk_edge, diff_risk_no_edge = 0, 0

# ran these combinations since we are picking 2 nodes out of N -> G(8) nodes
for u, v in combinations(G_8.nodes(), 2):
    connected = G_8.has_edge(u, v)
    same_gender = G_8.nodes[u]['Gender'] == G_8.nodes[v]['Gender']
    same_risk = G_8.nodes[u]['Risk']   == G_8.nodes[v]['Risk']

    if same_gender and connected: same_gender_edge += 1
    if same_gender and not connected: same_gender_no_edge += 1
    if not same_gender and connected: diff_gender_edge += 1
    if not same_gender and not connected: diff_gender_no_edge += 1

    if same_risk and connected: same_risk_edge += 1
    if same_risk and not connected: same_risk_no_edge   += 1
    if not same_risk and connected: diff_risk_edge += 1
    if not same_risk and not connected: diff_risk_no_edge += 1

In [ ]:
# gender df
gender_df = pd.DataFrame(
    [[same_gender_edge, same_gender_no_edge],
     [diff_gender_edge, diff_gender_no_edge]],
    index = ['Same Gender', 'Different Gender'],
    columns = ['Edge', 'No Edge']
)

# risk df
risk_df = pd.DataFrame(
    [[same_risk_edge, same_risk_no_edge],
     [diff_risk_edge, diff_risk_no_edge]],
    index = ['Same Risk', 'Different Risk'],
    columns = ['Edge', 'No Edge']
)

In [ ]:
risk_df

                Edge  No Edge
Same Risk         25       77
Different Risk    20       88

In [ ]:
gender_df

                  Edge  No Edge
Same Gender         19       83
Different Gender    26       82

#### P1; E

Create an additional contingency table where the entries count how many edges
observed in the network go between nodes with the same or different genders vs. how many edges in the network go between nodes with the same or different risk status. For example, an edge between two female students where one is at risk and one isn’t would go in the cell for same gender/different risk.

In [ ]:
same_gender_same_risk, same_gender_diff_risk = 0, 0
diff_gender_same_risk, diff_gender_diff_risk = 0, 0

for u, v in G_8.edges():
    same_gender = G_8.nodes[u]['Gender'] == G_8.nodes[v]['Gender']
    same_risk = G_8.nodes[u]['Risk'] == G_8.nodes[v]['Risk']

    if same_gender and same_risk: same_gender_same_risk += 1
    if same_gender and not same_risk: same_gender_diff_risk += 1
    if not same_gender and same_risk: diff_gender_same_risk += 1
    if not same_gender and not same_risk: diff_gender_diff_risk += 1

In [ ]:
gender_risk_df = pd.DataFrame(
    [[same_gender_same_risk, same_gender_diff_risk],
     [diff_gender_same_risk, diff_gender_diff_risk]],
    index   = ['Same Gender', 'Different Gender'],
    columns = ['Same Risk', 'Different Risk']
)

In [ ]:
gender_risk_df

                  Same Risk  Different Risk
Same Gender              11               9
Different Gender         15              11

#### P1; F

Write a brief summary of your network based on the measurements you’ve made so
far. Does there appear to be any association between these variables in your network? Which of the measurements above is most informative for addressing this question? Were you surprised by any of the results?

## Part 2

#### P2; A

In [ ]:
# container variable to help store the variables info
rows = []

for u, v in combinations(G_8.nodes(), 2):
    edge = int(G_8.has_edge(u, v))
    same_gender = int(G_8.nodes[u]['Gender'] == G_8.nodes[v]['Gender'])
    same_risk = int(G_8.nodes[u]['Risk'] == G_8.nodes[v]['Risk'])

    # number of shared friends
    shared_friends = len(list(nx.common_neighbors(G_8, u, v)))

    rows.append([u, v, edge, same_gender, same_risk, shared_friends])

In [58]:
pairs_df = pd.DataFrame(rows, columns=['node i', 'node j', 'edge', 'same gender', 'same risk', 'shared friends'])

pairs_df.head()

   node i  node j  edge  same gender  same risk  shared friends
0   40316   40310     1            1          0               0
1   40316   40312     1            1          0               1
2   40316   40318     0            0          1               2
3   40316   40321     1            0          0               1
4   40316   40301     0            1          1               0

#### P2; B

In [84]:
# will be using scikit-learn for logistic models
from sklearn.linear_model import LogisticRegression

y = pairs_df['edge']

# logistic model 1 w/ same gender + same risk
X1 = pairs_df[['same gender', 'same risk']]
model1 = LogisticRegression(penalty=None, class_weight='balanced').fit(X1, y) # turn off penalty (regularization not applied)

# added this class weight = 'balanced' parameter because both models had the same accuracy score
# model was not learning --> tune the model to "study" the data

print("model 1 coefficients:")
print(f"intercept: {model1.intercept_[0]:.4f}")
print(f"same gender (B1): {model1.coef_[0][0]:.4f}")
print(f"same risk (B2): {model1.coef_[0][1]:.4f}")

# logistic model 2 w/ same gender + same risk + shared friends
X2 = pairs_df[['same gender', 'same risk', 'shared friends']]
model2 = LogisticRegression(penalty=None, class_weight='balanced').fit(X2, y) # turn off penalty (regularization not applied)

print("\nmodel 2 coefficients")
print(f"intercept: {model2.intercept_[0]:.4f}")
print(f"same gender (B1): {model2.coef_[0][0]:.4f}")
print(f"same risk (B2): {model2.coef_[0][1]:.4f}")
print(f"shared friends (B3): {model2.coef_[0][2]:.4f}")

model 1 coefficients:
intercept: -0.0317
same gender (B1): -0.3140
same risk (B2): 0.3460

model 2 coefficients
intercept: -0.1763
same gender (B1): -0.3078
same risk (B2): 0.3734
shared friends (B3): 0.1560

#### P2; C

i wouldn't really say i'm too surprised, but it is interesting to get these results. our second model (logistic regression with the same gender, same risk, and same shared friends) performed better than the first model that had just taken into account the same gender and same risk as predictor variables. Since this jumped the accuracy by about 4%, we can say transitivity (shared friends) is an important feature to look at when we build our logistic regression model. --> later on build MCMC w/ specific thetas for these variables to score our models.

In [83]:
# accuracy score gets this proportion
from sklearn.metrics import accuracy_score

prop1 = accuracy_score(y, model1.predict(X1))
prop2 = accuracy_score(y, model2.predict(X2))

print(f"model 1 Accuracy: {prop1:.4f}")
print(f"model 2 Accuracy: {prop2:.4f}")

model 1 Accuracy: 0.5381
model 2 Accuracy: 0.5810